### ISSUE TITLE
"self" does not exist

### ISSUE THREAD

**Issue by kevart** [myfreeweb/httpotion#106]
I am new to erlang/elixir. I am currently going through the examples. Executing the async http call:

`HTTPotion.get "http://httpbin.org/get", [stream_to: self]`

in my console (iex -S mix) gives me this warning:

`variable "self" does not exist and is being expanded to "self()", please use parentheses to remove the ambiguity or change the variable name`

I assume _self_ has changed to _self()_ in current versions?

**Comment by myfreeweb** [comment]
Yeah, probably.
