### ISSUE TITLE
Redirect not working for localhost

### ISSUE THREAD

**Issue by Langhaarzombie** [myfreeweb/httpotion#120]
Dear HTTPotion Team,

I have a server running on localhost that redirects my post request to a get. The redirect on the server works, however, from HTTPotion I only get the 303 error as it cannot handle it.

As far as I can tell, the method for handling redirects has a bug in the url parsing part:

```elixir
defp normalize_location(location, url) do
  if String.starts_with?(location, "http") do
    location
 else
    Regex.named_captures(~r/(?<url>https?:\/\/.*?)\//, url)["url"] <> location
  end
end
```

When trying to parse `localhost:4321` as an url the Regex expression results in `nil` and is therefore unable to redirect correctly.

Thanks for your help!

**Comment by Langhaarzombie** [comment]
For everyone who has the same problem. Here is my workaround at the moment:

```elixir
response = HTTPotion.post(url <> "/postroute", [body: data])
result = HTTPotion.get(url <> response.headers.hdrs["location"])
```

This, however, only works when your server gives you the relative path (so without `localhost:4321`) as the redirect location.

**Comment by myfreeweb** [comment]
A better workaround would be to request `http://localhost:4321`.

But yeah lol that whole function looks weird. I'll replace it with `URI.merge`.

**Comment by myfreeweb** [comment]
Try current master now.

**Comment by Langhaarzombie** [comment]
It kinda works. So merging the two URI parts of course works, however, omitting *http* at the beginning is still not possible as the URI library only lets you merge absolute URIs. I do not know, if you even want that to be possible. 

I am going to stick with adding the protocol to the URI, so I am fine. Still, I would be happy to see the other option to be possible as well.

Also I forgot to add the `follows_redirect: true` option to the post request. After that it worked fine with `http://localhost:4321` as URI.

**Comment by myfreeweb** [comment]
hmm, yeah, so in general, it's undecidable whether to parse `example.com/abc` as `host: "example.com", path: "/abc"` or as a relative path `host: "", path: "example.com/abc"`, because paths can contain dots. Which is why you should never return something like `example.com/abc` in a `Location` header. Either return a relative path, or a full absolute one with the protocol.
