### ISSUE TITLE
Getting this issue without further explanation...

### ISSUE THREAD

**Issue by iojupiter** [myfreeweb/httpotion#124]
Erlang/OTP 20
Elixir (1.5.1)
:httpotion, "~> 3.1.0"

`HTTPotion.get! "google.ch"`
`** (HTTPotion.HTTPError) ehostunreach`
    `(httpotion) lib/httpotion.ex:453: HTTPotion.request!/3`

If I test a port on local machine it works fine.
 Please aid

_Originally posted by @iojupiter in https://github.com/myfreeweb/httpotion/issue_comments#issuecomment-425752880_

**Comment by myfreeweb** [comment]
Is the host reachable from other http clients?

**Comment by iojupiter** [comment]
Yes, for example `wget` and `cURL` behave as they must.

This issue came about when I transferred a project from elixir 1.4 to 1.5.
On the project running on 1.4 - HTTPotion behaves as it must.

This morning I did the whole transfer again to make sure I didn't misspell anything or leave out any dependencies. However it's still returning `%HTTPotion.ErrorResponse{message: "ehostunreach"}`

**Comment by iojupiter** [comment]
List of query attempts and their results:

httpbin.org
`HTTPotion.get "https://httpbin.org/get"`
=> we get a correct response

Some random app on host machine
`HTTPotion.get "192.168.8.100:9000"`
=> we get a correct http response

`HTTPotion.get "google.com"`
=> `%HTTPotion.ErrorResponse{message: "ehostunreach"}`

`HTTPotion.get "https://www.google.com"`
=> `%HTTPotion.ErrorResponse{message: "ehostunreach"}`



Additionally, on the previous application instance (1.4), this came about:
`iex(3)> HTTPotion.get "https://httpbin.org/get"`
`%HTTPotion.ErrorResponse{message: "{:tls_alert, 'internal error'}"}`
`iex(4)> 
16:56:59.433 [info]  ['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'hello', 32, 'received SERVER ALERT: Fatal - Internal Error', 10]`


How does HTTPotion interact with TSL?

**Comment by myfreeweb** [comment]
httpotion just uses [ibrowse](https://github.com/cmullaparthi/ibrowse) which uses the default Erlang/OTP implementation of TLS

**Comment by otoyo** [comment]
I sent the patch at #125 
Please review it.
