### ISSUE TITLE
process_request_headers does not have access to the request body

### ISSUE THREAD

**Issue by lizziepaquette** [myfreeweb/httpotion#127]
Sometimes the request header depends on the body. I propose adding an override-able function ```def process_request_headers(header, body), do: headers```. It would require only minimal change here:

https://github.com/myfreeweb/httpotion/blob/c79314b91df2cc8e43835b509efd682820d87fb4/lib/httpotion.ex#L149

and could be used in parallel with `process_request_headers/1` much like`def process_response_body(body)` and `def process_response_body(_headers, body)` do today.

**Comment by myfreeweb** [comment]
oh yeah, we can do that in a backwards compatible way, cool. Do you want to send a pull request for this?

**Comment by lizziepaquette** [comment]
yep! https://github.com/myfreeweb/httpotion/pull/128

**Comment by myfreeweb** [comment]
merged.

By the way, GitHub can [auto close issues if you say "fixes #number" in a PR description or commit message](https://help.github.com/en/articles/closing-issues-using-keywords) :)
