### ISSUE TITLE
process_request_headers doesn't have access to options

### ISSUE THREAD

**Issue by iilyak** [myfreeweb/httpotion#129]
We would like to inject additional headers depending on options. In particular we have the following [extract from here](https://github.com/apache/couchdb/blob/master/test/elixir/lib/couch.ex#L62:L79)
```
def process_request_headers(headers, options) do
    case Keyword.get(options, :cookie) do
      nil ->
        headers
      cookie ->
        Keyword.put(headers, :Cookie, cookie)
    end
end
```

Unfortunately in order to achieve that we have to [override](https://github.com/apache/couchdb/blob/master/test/elixir/lib/couch.ex#L167:L228) `process_arguments/3` function. Which is quite complex. 

I've noticed that recently the https://github.com/myfreeweb/httpotion/pull/128 was merged. Which modifies the signature of process_request_headers to support passing body. 
Would it be possible to use similar approach and implement
```
def process_request_headers(headers, _body, _options), do: process_request_headers(headers)
```

```
@@ -146,7 +148,7 @@ defmodule HTTPotion.Base do
        headers    = Application.get_env(:httpotion, :default_headers, [])
                     |> Keyword.merge(Keyword.get(options, :headers, [])
                       |> Enum.map(fn ({k, v}) -> { (if is_atom(k), do: k, else: String.to_atom(to_string(k))), to_string(v) } end))
-                     |> process_request_headers(body)
+                     |> process_request_headers(body, options)
```

**Comment by myfreeweb** [comment]
of course, would you like to send a PR?

// wow, couchdb test suite :)
