### ISSUE TITLE
Cannot make any get requests

### ISSUE THREAD

**Issue by yeehaa123** [myfreeweb/httpotion#13]
When I try to make a get request (for example HTTPotion.get("http://www.google.com")) I get the following error / stacktrace:

```
** (ArgumentError) argument error
 stacktrace:
   :ets.lookup(:ibrowse_lb, {'www.google.nl', 80})
   src/ibrowse.erl:317: :ibrowse.send_req/6
   deps/httpotion/lib/httpotion.ex:123: HTTPotion.request/5
   lib/octolixir/parser.ex:11: Octolixir.Parser.parse_gist/1
   test/parser_test.exs:14: ParserTest."test parse_gist should return succesfully with a valid id"/1
```

Anyone knows what's going on?

**Comment by gkop** [comment]
What do you think about mentioning `HTTPotion.start` in the README? And incidentally, where would you put HTTPotion.start, in, say, a phoenix app?

**Comment by myfreeweb** [comment]
@gkop It should be mentioned! I think it even was mentioned at some point...?

I guess it should go into app deps in `mix.exs`:

```elixir
  def application do
    [mod: {HelloPhoenix, []},
      applications: [:phoenix, :cowboy, :logger, :httpotion]]
  end
```

Please test it and tell me whether it works!

**Comment by gkop** [comment]
@myfreeweb yes, it works, thank you!

**Comment by collegeimprovements** [comment]
I'm getting error even after running:
```elixir
mix deps.get
iex -S mix
```
<img width="545" alt="screen shot 2016-02-15 at 12 38 46 pm" src="https://cloud.githubusercontent.com/assets/1519705/13041861/1d0d1380-d3e1-11e5-8222-f26c0b885a2c.png">


The error is:
```elixir
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:ibrowse_lb, {'www.google.com', 80})
             src/ibrowse.erl:328: :ibrowse.send_req/6
             lib/httpotion.ex:295: HTTPotion.request/3
```

**Comment by jpbecotte** [comment]
@collegeimprovements You need to start httpotion, either with `HTTPotion.start` as mentioned by @kwijibo or if you use phoenix, see @myfreeweb 's comment.

**Comment by collegeimprovements** [comment]
It solved my issue. Thanks.
