### ISSUE TITLE
Retiring HTTPotion on Hex

### ISSUE THREAD

**Issue by kolljohnson** [myfreeweb/httpotion#133]
I noticed that HTTPotion is now soft-deprecated, but currently this is listed only on GitHub. Hex recommends [retiring a package](https://hex.pm/docs/faq#can-packages-be-removed-from-the-repository) with `mix hex.retire` when a package has been deprecated or isn't actively maintained.
I believe there's also a `--message` option for recommending Tesla like on GitHub here!
 
> Instead of unpublishing we recommend to instead retire a package or release. This should be done if the maintainers no longer recommend its use, because it does not work, has security issues, been deprecated or any other reason. A package is retired with the mix hex.retire task. A retired package will still be resolvable and fetchable *but users of the package will get a warning a message and the website will show the release as retired.

**Comment by asterite** [comment]
In addition to this, I'd like to notice that if what you are consuming is a big chunk of data (for example 50MB) then HTTPotion will consume around 3GB of memory (!). And it's the same thing with Tesla.

So I wouldn't recommend using Tesla either.

I'd recommend using, for example, hackney.

**Comment by myfreeweb** [comment]
Sure, done.

---

@asterite does this happen with any tesla adapter? was this debugged? was this reported?

**Comment by asterite** [comment]
Sorry, I reproduced it in one of my projects but now I don't have time to create a small example to share. But it's basically, create a web server (in any language) that serves about 50M of content, and try fetching that from HTTPoiton or Tesla (default config, I didn't change anything) and you'll see the memory balloon to around 3GB.

**Comment by myfreeweb** [comment]
Well, tesla's default backend is httpc, you should try the hackney backend
