### ISSUE TITLE
Strip authorization from headers on redirects

### ISSUE THREAD

**Issue by lizziepaquette** [myfreeweb/httpotion#135]
When follow redirects is set to true, sensitive headers are forwarded to hosts that the sender did not anticipate. 

I've drafted a quick fix here: https://github.com/myfreeweb/httpotion/pull/134, an extension would be to mimic curl's --location-trusted flag and give users the option. 

See a similar issue w/ more in depth explanation here: 
https://github.com/chef/chef/issues/6984

**Comment by valpackett** [comment]
Thanks! I've merged #134. But note that httpotion is sort of deprecated, I myself am using [Tesla](https://github.com/teamon/tesla) with hackney backend now :)
