### ISSUE TITLE
How to do a multipart form post?

### ISSUE THREAD

**Issue by D1plo1d** [myfreeweb/httpotion#43]
It's not covered in the docs but is there any way I can send some kind of mapping of keys and values for a multipart form post body to httpotion without writing the whole post body out as a string?

**Comment by myfreeweb** [comment]
Looks like ibrowse itself doesn't have this functionality, we'll have to implement it here...

**Comment by myfreeweb** [comment]
So I've been thinking about this and I realized that it should be a separate library. We don't have any special support for JSON and other formats here – why should multipart/form-data be an exception?
