### ISSUE TITLE
next hex.pm release?

### ISSUE THREAD

**Issue by adamkittelson** [myfreeweb/httpotion#44]
I was just wondering when you were planning to push another release to hex.pm? I'd like to use some of the features in master in one of my libraries but I can't have a hex package with gitref dependencies.

Thanks!
Adam

**Comment by myfreeweb** [comment]
2.0.0 published! It's not backwards compatible (hence the major version number increment), but it shouldn't be too hard to change your code (`post(url, body, headers, options)` becomes `post(url, [body: body, headers: headers, other options...])`, etc.)
