### ISSUE TITLE
How to handle async messages

### ISSUE THREAD

**Issue by ararog** [myfreeweb/httpotion#50]
I'm trying to handle async messages in my project, my first attempt was place a receive block inside module instead of function, the code never gets compiled.

    receive do

        %HTTPotion.AsyncChunk{ id: _id, chunk: _chunk } ->
            IO.puts _chunk |> to_string
    end

What I'm doing wrong? I'm assuming [stream_to: self] is sending messages to the module and a receive block should do the trick, but I can't compile the module.

Should I spawn a separate process for this module or create another module to handle the async messages? 

Note: The module is cowboy request handler.

**Comment by myfreeweb** [comment]
To the module?!

A module is just a namespace of functions! It's not something like an object/instance in other languages. How would it receive messages?

`self` refers to the current process. `receive` should be called from a function. It blocks. If you don't want to block in that process, you need to spawn a new process.

**Comment by ararog** [comment]
Thanks for your answer, a clear mistake from my side.

A last question, since on spawn function we can provide which function will handle the message, how do I know which function will handle the message when we specify stream_to: self?

**Comment by ararog** [comment]
I believe I found the answer to my own question, looks like transformer function will be called.

**Comment by myfreeweb** [comment]
`self` refers to the current process. The function you spawn will execute inside of a new process, and `self` inside it will refer to the new process.
