### ISSUE TITLE
Documentation around changing the timeout?

### ISSUE THREAD

**Issue by bradcypert** [myfreeweb/httpotion#53]
I'm trying to figure out a way to change the timeout and I'm have no idea how to do it, but the default is a little short. Please assist?

**Comment by myfreeweb** [comment]
Just set the `timeout` option like any other request option.

Is 5000 ms really that low? o_0

**Comment by bradcypert** [comment]
I'm getting large, large amounts of JSON over a somewhat flaky connection. It shouldnt be necessary to up the default, but sadly, in this case, it is.

Thanks, I'll look at the docs to see about setting request options.

**Comment by henrik** [comment]
Hm, is this in the current docs? I found out about it through this issue. @myfreeweb Would you accept a PR to get it into the README?

**Comment by myfreeweb** [comment]
I didn't add it? Oh dammit.

Of course I'll accept a PR :-)

**Comment by bradcypert** [comment]
Yay, my issue is helping others!

**Comment by henrik** [comment]
@myfreeweb Awesome :) It's in the docstrings but not in the README, and the docs don't seem to be published (e.g. on https://hexdocs.pm/httpotion). I'll make a PR against the README.

**Comment by myfreeweb** [comment]
Thanks! I didn't know about the hexdocs thing, because I don't really use Elixir for anything...

Added the docs now.

**Comment by henrik** [comment]
:thumbsup: Great! Thank you :)
