### ISSUE TITLE
ITunes sandbox url Seg faults erlang vm.

### ISSUE THREAD

**Issue by skylerparr** [myfreeweb/httpotion#55]
Yeah, you read that right. I can't believe it myself. Here's some of the pertinent information I've gathered:

$ iex
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)

iex> HTTPotion.start
{:ok, []}
iex> HTTPotion.post("https://sandbox.itunes.apple.com/verifyReceipt", [body: "", headers: ["Content-Type": "application/json"]])
28805 Segmentation fault: 11 

I've tried it with httpotion 2.0, 2.1, and master.  All the same result.

Side note: "https://buy.itunes.apple.com/verifyReceipt" works fine

**Comment by myfreeweb** [comment]
Have you tried that URL with ibrowse directly, without HTTPotion?

**Comment by skylerparr** [comment]
ibrowse is the culprit.  Thank you.

tracking:
https://github.com/cmullaparthi/ibrowse/issues/127

**Comment by skylerparr** [comment]
Ended up being an old version of erlang specific to OSX. I updated from 17.4 - 17.5 and it works just fine now. Thank you.
