### ISSUE TITLE
ibrowse hex package..interest?

### ISSUE THREAD

**Issue by bradleyd** [myfreeweb/httpotion#56]
I depend on HTTPotion and it would be nice if we could get ibrowse into hex to use that instead of git deps.  Any interest?

Take care,
Brad

**Comment by cloudbring** [comment]
I'm on it, feel free to ping me if you don't see it this week.

**Comment by bradleyd** [comment]
@cloudbring awesome.  I will close this ticket then.

**Comment by cloudbring** [comment]
Assign this to me and I'll update here when it's done.

**Comment by DavsX** [comment]
ping?

**Comment by bradleyd** [comment]
@cloudbring any status?

**Comment by cloudbring** [comment]
@DavsX @bradleyd It's on my todo list this week. Sorry, I got buried in a project last month. This is a the top of my open source task list.

**Comment by henrik** [comment]
This would be awesome – I was just wondering why users of this lib have to specify the ibrowse dependency themselves, and I guess it's because it is currently a GitHub dependency.

**Comment by myfreeweb** [comment]
@henrik yes, exactly

**Comment by henrik** [comment]
After some nudging, ibrowse is now in Hex :) https://github.com/cmullaparthi/ibrowse/issues/128
