### ISSUE TITLE
how can I use behind web proxy?

### ISSUE THREAD

**Issue by letusfly85** [myfreeweb/httpotion#57]
I want to use httpotion behind proxy.
Do you have any ideas?

**Comment by JustMikey** [comment]
Apparently they don't

**Comment by myfreeweb** [comment]
You can pass any options to [ibrowse](https://github.com/cmullaparthi/ibrowse) using the `:ibrowse` key in the options dict, like this:

```elixir
HTTPotion.get "http://ip6.me", [ ibrowse: [ proxy_host: 'fc81:6134:ba6c:8458:c99f:6c01:6472:8f1e', proxy_port: 8118 ] ]
```

I'll add this to the README, thanks for asking.
