### ISSUE TITLE
Get with Digest Auth?

### ISSUE THREAD

**Issue by shankardevy** [myfreeweb/httpotion#60]
Would you be interested to have a Digest Auth PR similar to basic auth? I will be interested to send one.

```elixir
iex> response = HTTPotion.get "httpbin.org/basic-auth/foo/bar", [basic_auth: {"foo", "bar"}]
```

```elixir
iex> response = HTTPotion.get "httpbin.org/digest-auth/foo/bar", [digest_auth: {"foo", "bar"}]
```
Seems like erlang library ibrowse is already supporting this, but need to look into detail.

https://github.com/cmullaparthi/ibrowse/blob/master/src/ibrowse_http_client.erl#L936-L939

**Comment by myfreeweb** [comment]
Of course I'm interested :-)

That function in ibrowse is not digest auth though... If you look a couple lines higher: `{"Authorization", ["Basic ", http_auth_digest(U, P)]}` And just, like, look at it – it does no hashing ("digest"), just base64.

So you'd have to write it from scratch.

P.S. You should send a pull request to ibrowse that renames it to `http_auth_basic`!

**Comment by shankardevy** [comment]
thanks @myfreeweb . I have given a PR for renaming here: https://github.com/cmullaparthi/ibrowse/commit/e478d010259fcc2558afec7b50712d0507710ed7

and I am working on supporting Digest auth here: https://github.com/cmullaparthi/ibrowse/commit/d8b9331688820d8a05e995d002dc7a0cd1cee339

**Comment by myfreeweb** [comment]
Nah, you won't need to change their public API. Passing `basic_auth` to ibrowse is just a convenience thing. Auth is **just a header**!

Just do it like `headers = Dict.put(headers, "Authorization", "Digest ... ... ...")`

**Comment by myfreeweb** [comment]
I see you're working on adding digest auth directly to ibrowse though... Yeah, if they accept that, it'll be even better.

**Comment by shankardevy** [comment]
@myfreeweb if this has to go into httpotion, could it be something like https://github.com/shankardevy/httpotion/commit/d2610908472b96ce736064c538ec21be38b5112d

can we have the digest_auth support directly on httpotion until ibrowse supports it? 

with the above commit, we would use digest_auth as
```elixir
 HTTPotion.get "http://localhost:3000/digest", [digest_auth: {"foo", "bar"}]
```

Sinatra app for running a digest_auth server is available at https://gist.github.com/shankardevy/535f48fb4583425049c3

PS: the commit is still WIP. nonce value needs to be secure, which isn't now.
