### ISSUE TITLE
ibrowse fail to compile on Erlang 18

### ISSUE THREAD

**Issue by narkisr** [myfreeweb/httpotion#62]
==> ibrowse (compile)
Compiling src/ibrowse_lib.erl failed:
src/ibrowse_lib.erl:371: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
ERROR: compile failed while processing /home/ronen/code/octo/deps/ibrowse: rebar_abort
** (Mix) Could not compile dependency ibrowse, /home/ronen/.mix/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile ibrowse

Is the only solution is to use Erlang 17?

**Comment by myfreeweb** [comment]
Looks like they've fixed it. Remove the release tag on ibrowse in your deps, use master instead for now.

**Comment by narkisr** [comment]
Seems to be working thanks

**Comment by myfreeweb** [comment]
You can switch to a release now, see #66

**Comment by narkisr** [comment]
Cool, thanks!
