### ISSUE TITLE
process_response_body not called when async?

### ISSUE THREAD

**Issue by andrewbranch** [myfreeweb/httpotion#64]
I'm super new to Elixir, so this may be by design, or it may be something I'm doing wrong, but it appears that `process_response_body` isn't called on the `chunk` in async requests, whereas it does get called in a synchronous request. What's the reason for this discrepancy?

**Comment by myfreeweb** [comment]
Well, you can't call `process_response_body` because it might expect, you know, the whole body – and you don't have it yet when you're receiving chunks.

For chunks, there is the creatively named `process_response_chunk` function.

I'll add this to the README.
