### ISSUE TITLE
Unicode support?

### ISSUE THREAD

**Issue by werbitzky** [myfreeweb/httpotion#65]
I talk to a server using HTTP get and the response is an UTF-8 encoded JSON string. When decoding it with Poison, special unicode characters do not get decoded in the right way, so I and up with odd output. Can we do something about this or is this an issue with `ibrowse`?

https://github.com/edgurgel/httpoison does not have this problem – it in turn uses hackney instead of ibrowse

**Comment by myfreeweb** [comment]
Hi!

Could you please provide an example of *special* characters? UTF-8 should work:
![screen shot 2015-07-26 at 6 38 13 pm](https://cloud.githubusercontent.com/assets/208340/8894606/8695249e-33c5-11e5-8093-a7234d5485aa.png)

**Comment by werbitzky** [comment]
Thank you so much for the quick reply!

So I looked into it a bit further, and I don't quite get the problem, but apparently it is much more specific (sorry about the lack of information at first):

I'm on Elixir 1.0.4, newest version of HTTPotion, ibrowse v4.1.1

I have the following code:

```elixir
defmodule Elastix.HTTP do
  @moduledoc """
  """
  use HTTPotion.Base

  @doc false
  def process_request_headers(headers) do
    headers
    |> Dict.put(:"Content-Type", "application/json")
  end

  @doc false
  def process_response_body(body) do
    body = to_string(body)
    case Poison.decode body do
      {:error, _} -> body
      {:ok, decoded} -> decoded
    end
  end
  
  @doc false
  def host, do: Elastix.config(:elastic_url)
end
```

now I'm doing:

```elixir
Elastix.HTTP.get("https://www.openthesaurus.de/synonyme/search?q=test&format=application/json")
```

It should return an "ü" in the response, for the german word "Pr**ü**fung" but it returns "PrÃ¼fung"

**Now**, strangely, if I uncomment the part ```body = to_string(body)``` in the ```process_response_body(body)``` function, leading to the following code, I get the right encoding for "Prüfung":

```elixir
  @doc false
  def process_response_body(body) do
    # COMMENTED OUT:
    #body = to_string(body) 
    case Poison.decode body do
      {:error, _} -> body
      {:ok, decoded} -> decoded
    end
  end

```

**Comment by myfreeweb** [comment]
`to_string` is deprecated... and, like, there's a new `to_string` that's actually for converting anything into strings... I don't know anymore.

What I do know is that the default `process_response_body` calls [`IO.iodata_to_binary`](http://elixir-lang.org/docs/v1.0/elixir/IO.html#iodata_to_binary/1).

Sorry for not updating the README example! Going to do it now.

I don't know what `Poison.decode` is, but maybe it expects iodata?

**Comment by werbitzky** [comment]
Thank you for the update!

I red about strings, binaries and iodata and now I understand the underlying problem, so for completeness:

Poison is a JSON library for Elixir, it expects an **Elixir string** (which is an UTF-8 encoded **binary**)

The data, that `process_response_body` receives as the `body` argument is `iodata` which is a `list` of bytes, so more like a *"binary represented by a list"*:

binary: `<<104, 101, 197, 130, 197, 130, 111, 0>>`
iodata: `[104, 101, 197, 130, 197, 130, 111, 0]`

By calling `to_string/1` on this list of bytes, Elixir however thinks it is a `char_list` which in turn would be a list of code points (which can contain higher values than 255), so `to_string/1` interprets each code point in the list as a single character and like this breaks the UTF-8 encoding.

char_list: `[322, 122, 33, ...]`
