### ISSUE TITLE
Follow redirects automatically?

### ISSUE THREAD

**Issue by henrik** [myfreeweb/httpotion#67]
Is there some option to automatically follow redirects?

If not, and if it's something you'd consider adding, then consider how it affects async requests. For my particular use (https://github.com/henrik/sipper/blob/3ed53333fbffe5ed68bf27c5751f82cf17970d56/lib/sipper/dpd_cart_client.ex), it would be convenient if only the last request in the chain sent async messages. But maybe that's not sensible behavior in general – I don't know.

**Comment by myfreeweb** [comment]
No, it's not implemented :-( I can't believe nobody complained about it earlier.

Feel free to do it and send a PR!

**Comment by henrik** [comment]
Cool! Focusing on hacking on some other stuff ATM but if no one else beats me to it (please do), I might try to PR this some day.

**Comment by zodiac** [comment]
I'm interested in working on this.

Should the default be to follow redirects or not? How do you pass an option to specify whether to follow?

**Comment by henrik** [comment]
@zodiac Awesome! Had a look at HTTParty (a lib for Ruby) and it follows redirects by defaults. But I'm not sure which is the more common use case. I'd be happy having it at all, even if it's opt-in.

It also seems to have a concept of a max number of redirects to follow, and configurability around HTTP methods and redirects. Those are probably not musts but might be nice to have if you want some inspiration: https://github.com/jnunemaker/httparty/blob/master/lib/httparty.rb

**Comment by myfreeweb** [comment]
Hey! The work is going on in PR #71 :-)
