### ISSUE TITLE
process_arguments spec: options argument seems to be no longer a Dict.t 

### ISSUE THREAD

**Issue by weaktyper** [myfreeweb/httpotion#78]
[On line 92](https://github.com/myfreeweb/httpotion/blob/master/lib/httpotion.ex#L92)
The options `Dict.t` in the spec is not longer supported since the `Keyword` module is being used to parse the options now rather than the `Dict` module. I was using maps for the options those are no longer supported. Seems to be the `[Keyword]` type in the latest version I think.

[recent changes](https://github.com/myfreeweb/httpotion/commit/6dcf253c74b8d2ff67ffe67548a327db919732c7)

**Comment by myfreeweb** [comment]
Thanks!

Used Dialyzer on the project. It didn't complain about that (but I've changed the type to `[{atom(), any()}]`) – however it caught a bug in #77 :)
