### ISSUE TITLE
Get source after Javascript is run

### ISSUE THREAD

**Issue by zamith** [myfreeweb/httpotion#79]
Is it possible to get the source of a page after javascript has been run? I keep getting the pre-JS source which does not have the data I expect it to have.

Thanks.

**Comment by myfreeweb** [comment]
No! HTTP client libraries don't do that.

You can't just "run JavaScript", you basically need a browser. Try a headless browser like [PhantomJS](http://phantomjs.org) or [SlimerJS](https://slimerjs.org).
