### ISSUE TITLE
Access protocol compilation warning

### ISSUE THREAD

**Issue by filipecabaco** [myfreeweb/httpotion#81]
On compilation the following warning is thrown:

`lib/httpotion.ex:292: warning: implementation of the Access protocol is deprecated. For customization of the dict[key] syntax, please implement the Dict behaviour instead`

PR that corrects this:
https://github.com/myfreeweb/httpotion/pull/80

**Comment by myfreeweb** [comment]
Please don't create issues like this! A PR is already an issue. You shouldn't create an issue that links to the PR you just created.
