### ISSUE TITLE
Return ErrorResponse instead of raise

### ISSUE THREAD

**Issue by bradleyd** [myfreeweb/httpotion#82]
I was wondering if you would accept a PR to change the behavior when ibrowse sends an error tuple, httpotion would return an `%ErrorResponse{}` struct.  It could still `raise` an error if the `!` version of the function is called.

The main reason for this is to avoid using costly `try/rescue` in the calling code.  Another reason, is to keep it idiomatic with other erlang/elixir libraries (least amount of surprise)

Thoughts?  

Thanks for putting the work into this library!

Brad

**Comment by myfreeweb** [comment]
@bradleyd Yeah, that makes sense.
