### ISSUE TITLE
Can we have a release please?

### ISSUE THREAD

**Issue by notgary** [myfreeweb/httpotion#88]
The work done in https://github.com/myfreeweb/httpotion/commit/c2ed54f28bf020541653c39c52f50457dd542004 will be useful to use. We can remove our exception handling of `HTTPError` and add `ErrorResponse` as just one more possible return value in our case statement.

Would you be able to release what is currently in master please?

**Comment by myfreeweb** [comment]
Fine :) Released 3.0.0.

**Comment by notgary** [comment]
Thanks very much 👍
