### ISSUE TITLE
HTTP redirects are broken

### ISSUE THREAD

**Issue by stevegraham** [myfreeweb/httpotion#94]
`:follow_redirects` will not be picked up from `process_options/1` or the default option from the application env.

Also the semantics of HTTP redirects are not followed, e.g. 303 should be a GET redirect, HTTPotion uses the same HTTP method.

**Comment by myfreeweb** [comment]
Please make a pull request that changes `options[:follow_redirects]` to `args[:follow_redirects]` and adds the missing semantics :)

**Comment by stevegraham** [comment]
I don't use this library anymore. It's up to you if you want to fix the issue or leave it as is.

**Comment by myfreeweb** [comment]
The first part has been fixed in #101.

**Comment by arturictus** [comment]
Hi, how is this going?
do you need any help this this Issue?
can you guide me to fix it?

**Comment by myfreeweb** [comment]
@arturictus you can add the 303 semantics to the `if response_ok(response) && is_redirect(response) && args[:follow_redirects]` block :)

also look into making redirects work with async
