### ISSUE TITLE
Please Bump patch version with the code that fixes the compiler warnings

### ISSUE THREAD

**Issue by dokie** [myfreeweb/httpotion#95]
Hi

We have compiler warnings as errors in our code projects and as such, the fix you have made to `httpotion.ex` would greatly help us, but you didn't bump the version number to `3.0.1` or higher and so we cannot get this without referencing the GitHub repo in our `mix.exs` file which we usually don't support.

Can you release this patch soon please?

Many thanks
Mike

**Comment by myfreeweb** [comment]
done

**Comment by dokie** [comment]
Thanks 👍
