### ISSUE TITLE
Response headers are converted to atoms

### ISSUE THREAD

**Issue by schnittchen** [myfreeweb/httpotion#99]
Here: https://github.com/myfreeweb/httpotion/blob/master/lib/httpotion.ex#L73

Response headers are out of control of the application author and should be treated like user input. Converting string user input to atoms will eventually crash the machine. See also https://erlangcentral.org/wiki/index.php/Atom_Table

**Comment by myfreeweb** [comment]
Thanks! Released 3.0.2 with the fix.

**Comment by schnittchen** [comment]
That was swift! Thank you :)
